### ISSUE TITLE
Check if player has rights on claim? Plugin Development

### ISSUE THREAD

**Issue by eloo95** [TechFortress/GriefPrevention#1018]
Hello i am programming a blockbreaker plugin and would like to check with support of GriefPrevention if the player who sets up the blockbreaker has the rights on the claim or you can only create the blockbreaker on one claim. can anyone tell me what the function is called or is there a developer documentation for griefprevention somewhere?

**Comment by RoboMWM** [comment]
DataStore#getClaimAt

You could also consider trying a fake BlockBreakEvent too.
