### ISSUE TITLE
Defenseless player protection

### ISSUE THREAD

**Issue by Eilrahcrrod** [TechFortress/GriefPrevention#1071]
I'm working on a pvp server, and one of the modes is just hand-to-hand combat, but the plugin says "you can't hurt defenseless players". I've looked around the config multiple times and haven't found anything that may be able to fix it.  Is there a way to disable that?

**Comment by RoboMWM** [comment]
https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#pvp-configuration `PvP.ProtectFreshSpawns`
