### ISSUE TITLE
Issue: Does not alert player when they reach aquired limit.

### ISSUE THREAD

**Issue by TomLewis** [TechFortress/GriefPrevention#108]
Somehow 2 of my players managed to reach my very high acquired limit for claim blocks, it does not tell them when they hit the limit, it just stops them getting more. Could we please have this added.

**Comment by RoboMWM** [comment]
Things to consider in addon - when/where to notify player (claimlist? On accrual event? on holding shovel? etc.), and what threshold.

**Comment by FrozenBeard** [comment]
Did this get implemented anywhere?
