### ISSUE TITLE
How would I allow pistons to move globally

### ISSUE THREAD

**Issue by BeefPieGuy** [TechFortress/GriefPrevention#1091]
Hello, I've found the  'PistonMovement: CLAIMS_ONLY' Section, however was wondering what I would replace CLAIMS_ONLY wil to allow piston movement in all worlds.

**Comment by Jikoo** [comment]
PistonMovement options are documented [on the wiki](https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#pistonmovement).
