### ISSUE TITLE
Planted Trees can grow into other's claims

### ISSUE THREAD

**Issue by kitokofox** [TechFortress/GriefPrevention#152]
### What behaviour is expected:
Tree slices off/ not allowed to grow.
### What behaviour is observed:
Tree grew leaves into other's claim.
### Steps/models to reproduce:
Plant a tree adjacent to other's claim and then let it grow.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This can be found on any version.

**Comment by RoboMWM** [comment]
I remember seeing something in the commits about removing this since it's not that big of a deal & somewhat expensive(?)
