### ISSUE TITLE
[Suggestion] Add command for other [ all ] players to use villagers

### ISSUE THREAD

**Issue by iTaeyeonKim** [TechFortress/GriefPrevention#251]
Adding permission for [ all ] also can 1 player to use villagers, without giving access to kill them

**Comment by TheSenseiNL** [comment]
Make a sub claim with /subdivideclaim
Then in that subdivided claim do:  /containertrust ALL

That gives everyone access to traid with the villagers. I use that to

**Comment by RoboMWM** [comment]
Or just `/containertrust public` since it sounds like you're trying to apply this to a claim anyways.

Also I recommend using `public` instead of `all` since doing `/untrust all` removes everyone from the trustlist instead of just removing the `public` from it.

Thanks for the tip TheSenseiNL
