### ISSUE TITLE
Minecraft World Border to Display protected region

### ISSUE THREAD

**Issue by wasder** [TechFortress/GriefPrevention#273]
Feature request: make protected regions displayed with minecraft's world border. https://minecraft.gamepedia.com/World_border

Would not it be cool?

**Comment by RoboMWM** [comment]
Not possible. This would:

- Only work for a single claim
- Would prevent players from entering/exiting claim.

There were some other suggestions to use structure blocks and the like though. #46

**Comment by wasder** [comment]
- Only display, when you check claim with stick/shovel
- Hide it when get too close to the border
- Make it as addon?

**Comment by RoboMWM** [comment]
@bigpresh it's possible to use a fake worldborder to do all sorts of things (i.e. see the tinthealth project).

Sure, an addon would work with your given parameters.
