### ISSUE TITLE
/trapped command

### ISSUE THREAD

**Issue by sirlinium** [TechFortress/GriefPrevention#303]
Hello, please excuse me for posting wrong place...

would it be possible to be able to disable the /trapped use ?

many thanks !

**Comment by RoboMWM** [comment]
`griefprevention.trapped`

It's documented on the commands page, but not the permissions page, so if someone wants to update the permissions page with that that'd be appreciated.

**Comment by sirlinium** [comment]
I updated the page, thank you !
