### ISSUE TITLE
Multiple claims for different ranks

### ISSUE THREAD

**Issue by MrBuushy** [TechFortress/GriefPrevention#439]
Can you please add a feature that works with PEX/Any other group or rank plugin where imagine: You were Noob rank and you could only create 2 claims but then you bought a higher rank called Pro rank and that gave you 5 claims and then you upgrade to overlord rank and you get unlimited ranks.
If you did add this maybe in Config it should look like this:

MaximumNumberOfClaimsPerPlayer: 2
#This is where you choose what group gets what amount of claims, 0 = infinite
#If Enabled is set to False it will use MaximumNumberOfClaimsPerPlayer instead but if set to True it will not use MaximumNumberOfClaimsPerPlayer and use MaximumNumberOfClaimsPerGroup (Default = False)
#Groups shows the list of the groups with different claim amounts
MaximumNumberOfClaimsPerGroup:
  Enabled: False
  Groups:
    Noob: 2
    Pro: 5
    Overlord: 0

And the permission nodes were this:
"GriefPrevention.MaxClaims.Group.(Name of the group)" or
"GriefPrevention.MaxClaims.(Name of the group)"

so for the Noob group, i put this node into Pex for Noob rank:
"GriefPrevention.MaxClaims.Group.Noob" or
"GriefPrevention.MaxClaims.Noob"
--------------------------------------------------------------------------------------------------------------
                                            Or different way
--------------------------------------------------------------------------------------------------------------
#This is default amount of claims per player
DefaultMaximumNumberOfClaimsPerPlayer: 2

and the node would be for more "GriefPrevention.MaxClaims.(Number of Max claims)"

so say in PEX it will be
Groups:
  Noob:
    Permissions:
  Pro:
    Permissions:
    - GriefPrevention.MaxClaims.5
  Overlord:
    Permissions:
    - GriefPrevention.MaxClaims.0 (or GriefPrevention.MaxClaims.Infinite)

**Comment by BushGamingYT** [comment]
@RoboMWM do you know when the next update might come out?
