### ISSUE TITLE
Request: add FAWE/WE //regen parameter to /removeclaim -r

### ISSUE THREAD

**Issue by TomLewis** [TechFortress/GriefPrevention#492]
I wish the resotre nature would just use worldedit/fawe and do a //regen.
So have an option that when deleting a claim /removeclaim -r there's a parameter to regen it too (not auto) that would just make that WE selection (fawe allows console based pos1 and pos2 and regen) and do the fawe/WE //regen.

**Comment by 112madgamer** [comment]
This can be done in my GP addons plugin

**Comment by FrozenBeard** [comment]
@112madgamer This would be fantastic, is there a list of features in your GP addons plugin?

**Comment by 112madgamer** [comment]
Yeah, check the GriefPreventionUtilities on my profile. The /edeleteclaims deletes all claims inside your WG region

**Comment by RoboMWM** [comment]
@112madgamer feel free to link/add a short description of your addon in the addons page on the wiki
