### ISSUE TITLE
Claimexplosions can be enabled by players with build trust

### ISSUE THREAD

**Issue by WiIIiam278** [TechFortress/GriefPrevention#618]
/ClaimExplosions can be executed by players within a claim to modify explosions. I was under the impression players with permission trust were only able to execute this command, and so on our server an issue elapsed where a builder enabled them while trying to disable them by accident when placing large amounts of TNT as a prank, flattening an entire subclaim.

It seems like a weird choice to have claimexplosions able to be toggled by builders.

**Comment by SydMontague** [comment]
This also applies to adminclaims. I don't want players to be able to manage admin claims...
