### ISSUE TITLE
GP v20 discussion thread

### ISSUE THREAD

**Issue by RoboMWM** [TechFortress/GriefPrevention#63]
# The version 20 update discussion "thread"

Be sure to hit that subscribe button on the right if you want notifications with what's happening for version 20. Feel free to report any issues with v20 as a comment in this ticket, or in IRC chat.

# Direction update (5/25/2020)

v20 has been going along for quite some time, and I pushed a couple updates today. Considering all the work that has gone into this, I'm thinking it may be a better approach to slowly migrate GP itself over to look something like this, instead of doing a full-on replace. There is a lot to implement, and nobody has tested (or at least provided any feedback), so it really isn't feasible to continue developing an entirely-separate version of GP.

I'm looking for feedback on this, but here's one idea of how it could go:

I'd start with non-impactful backend refactors. Mostly just code cleanup such as breaking massive classes into smaller classes, implementing the GP events and "funnel" system, etc. The current state of the dev/v20 branch will basically be used as the blueprint for this step.

Then I'd move into more major changes, e.g. modifying the database interface, modifying the config, removing hardly-used features, etc. I'm thinking at this point I'd need to break off into a v20 branch and publish betas due to the feature removal - but one way or another, I'm thinking we'll need a hard break from the less-used features; I don't think it'll be worth the time to constantly be writing migration functions to preserve the configuration settings for these features.

Lastly, after the codebase is mostly clean and contained, there will be a major focus on re-adding removed features or exposing parts of GP that make it easy to add these features back as addons.

---

# (One of) the reasons why this is happening and taking a long while
https://codeclimate.com/github/TechFortress/GriefPrevention

[![](https://i.imgur.com/pUxIlU0.png)](https://codeclimate.com/github/TechFortress/GriefPrevention)

That 6 month figure multiplies as new features and fixes to new MC versions roll out. And I'm assuming that figure assumes the project is a day job + has a team.

# Tracking progress

[It's on a GitHub projects board](https://github.com/TechFortress/GriefPrevention/projects/1)

Code progress can be tracked on the [dev/v20](https://github.com/TechFortress/GriefPrevention/commits/dev/v20) branch. And yes, if you'd like, you can help via PRs (though, please avoid adding features - cleaning/refactoring would be appreciated!) _Please note that I'm not interested in package structure changes in PRs_ - those suggestions should be discussed here. It also makes for an easier-to-follow diff.)

### Downloading test builds
Version 20 development builds can be downloaded from AppVeyor. Make sure you get a build that's built from the `dev/v20` branch!

**Warning! These builds are not safe to use on a production server!** Just in case you aren't aware of the current state of version 20 from reading the above.
https://ci.appveyor.com/project/RoboMWM39862/griefprevention/history

(I don't know how to sort builds based on branch. I'm assuming I'd have to make another appveyor project and webhook to do that. If someone wants to figure it out for me that'd be appreciated.)

### Chat
Additionally, if you want to chat with us, [we're on IRC! (and dumcord if that's your thing)](http://techfortress.robomwm.com/p/griefprevention-irc.html)

<details>
<summary>Old updates</summary>

Update 1/9/2019

GP v20 is now on alpha, alpha 2 to be specific. Download link has been added above! Future update notes will be in the comments - I'll probably prune this "update log" since edit history and comment hiding are now things in GitHub.

[Update 9/15/2018](https://github.com/TechFortress/GriefPrevention/issues/63#issuecomment-421655928)

Went ahead and decided to preserve /accesstrust, and is controlled via `GPToggleBlockStateEvent`. Probably will fold fire damage along with the /claimexplosions command.

Anyways, branch dev/v20 can now be compiled and run. Functionality is very barebones - currently no indication of claim borders or the like, but they can be created. If you want, you can test out its file saving and such - but I'm primarily looking for feedback on the API as of now. Is it sufficient?

ClaimClerk - a getter for this will exist in the main class, and provides access to GP's stored claims. It provides caching via requiring a Player object to be passed (though it also caches on the null key) on `#getClaim`

FlatFileStorage - playerdata and claimdata saves are done asynchronously and have a thread pool for each - any problems with thread safety/design here?

And of course, any other comments regarding any particular design/organization/etc.

---------

Update 6/24/2018

#### Polls:
- Remove /accesstrust: https://www.strawpoll.me/15962254
- Allow firespread from fires that originated within a claim: https://www.strawpoll.me/15962260

------

Update 2/13/2018

Mostly waiting for 1.13 to drop so I can build against that. In the meantime, will be finishing up the backend as much as I can before real life comes into full force or something.

As for legacy - unsure if that should remain as a separate branch (and thus the issue tracker will be for both?) or as a fork.

---

Update 1/3/2018
Yes there's still a lot of cleanup and core stuff to do first, however as I was rethinking of the refactor I might keep the other "antigrief" features such as pvp protection, chat spam prevention, etc., but in a basic form. Along with the "instruct players as they play" approach Big_Scary employed, the convenience for server owners interested in a simple, general antigrief solution that they can merely drop in their plugins folder is probably also one major factor that led to this plugin's popularity.

Things that are not "prevention"-based are still planned to be removed, especially since these things (i.e. restorenature) require updates when new biomes are released or changed, or are often requested to be augmented (siege, economy).

The modules will be in separate packages and will have a separate config file for each (PvP, Chat, Wilderness)

---

Update 12/23/2017
So yea, was busy with other life things those past few months. Fortunately it paid off; though, yes, next to no progress occurred with version 20. So yea, it's still a long way out, but since 16.8 has finally been released, I'll be diverting more attention to this for now.

---

Update 9/11/2017

There's a lot of (not-so-fun) work to do, so no hard-set ETA. Would ideally like to get something functional by the end of the year, but no promises.

Progress can be tracked on the [dev](https://github.com/TechFortress/GriefPrevention/commits/dev) branch. And yes, if you'd like, you can help via PRs (though, please avoid adding features - cleaning/refactoring would be appreciated!)

---

Update 6/10/2017

It has been discovered that Big_Scary is aware of this plugin's design monstrosity. https://forums.spongepowered.org/t/griefprevention-official-thread-1-8-9-1-10-2-1-11/1123/162

---

Update (April 25, 2017)

GP version 20 (what this ticket is primarily about):
- Will contain custom, generalized events to allow other plugins to override GP's behavior
- Will have a lot of API exposed (largely via events)
  - Encourages other plugin developers to create addons.
- Will only contain the necessary, "core" features
  - The other features will be released in addons. Some will be maintained by me (anti-spam, PvP, creative claims, more TBA).
- Will have more comprehensive logging.

#### What about the "old" GP?

GP version 16 (legacy):
- Is and will continue to be maintained in a separate fork/branch.
- Likely will not receive any new features from me, but others are free to PR to this version
  - Although I stated I likely will not add new features to the legacy version, I probably _will_ add more configuration options for existing features. (e.g. siege cooldown, entity limit for creative worlds)

---

So I recently solved an issue which involved me seeing how ugly this code is (probably years of different ways to implement something, in which the previous iterations haven't been fully discarded).

I'd like some input on how I should go about this. My current ideas regarding organization are to start moving methods out of the main class as well as potentially moving some methods out of the DataStore class. Probably some additional packages would be nice too - any ideas on how this should look?

Regarding implementation, it'd probably be best if doing things like resizing a claim wasn't similar to creating a new claim. Obviously I'll be getting rid of public variables (which may break some addons) and adding getters/setters. Not sure how you guys feel about the use of static throughout this entire project - I'm currently leaning towards getting rid of all this static use.

I'll likely be slowly implementing any ideas and plans gradually, and as always am accepting PRs for this as well.

---

Backend changes:
- refactored classes into packages, broke up multiple classes, etc.
- Eliminated static abuse.
- Claim IDs are determined via current system time instead of storing and loading a value.
</details>

**Comment by Jikoo** [comment]
The one thing I really want to see from GP is consistent versioning, which you appear to have in hand. Previous authors did not seem to understand that just because you hit micro version 9 does not mean the next version increases the minor version.

Regarding static: when used responsibly, it's a good tool. I chose to remove it from most plugins I maintain with a few exceptions because in most cases I prefer constructor dependency injection, but it's entirely up to you. I don't believe GP's use of static is horrible, but I don't remember too much of it off the top of my head.

As for where to start, I'd say create the getters and setters and feel it out from there. A lot of everything will probably need to be rewritten, but the overall structure seems pretty well-designed. Decide what features are core plugin features and cut the rest. History's always there thanks to version control, so people creating addons reintroducing removed features can easily look at the old code to see how it was implemented.

**Comment by RoboMWM** [comment]
So @BillyGalbreath mentioned another route that I was considering, rewriting a "core" and having some official addons (for antispam, pvp grief, etc.).

Seeing that I might take this route (since add setters/getters and making variables private is already going to break most addons), any suggestions for a new name? Some I came up with last night include GriefGuardian, BetterPreventer/BetterPrevention, GriefDefender (I kinda like GriefGuardian as it has the same syllable count and ends with an 'n'.)

**Comment by RoboMWM** [comment]
^ How does that look @Jikoo and @BillyGalbreath (and anyone else who's interested)?

GP will listen to these "abstracted" events at lowest priority in a separate class(es), and other plugins can respectively listen to and undo such if they so desire.

**Comment by Jikoo** [comment]
Looks good to me, sounds like a solid plan.

**Comment by BillyGalbreath** [comment]
I like it other than the priorities. Low is OK, I guess, because we can use lowest to do something first. However you said lowest, which makes it harder if not impossible to intercept. Undoing a GP action may cause issues under certain circumstances that won't become obvious until later (look back at uncancelling the resurrect event for example).

Also, if you get off the lowest priority you can add ignorecancelled true so plugin/add-on interception can happen smoothly. I'm on my phone so I can't provide a good example case, but off the top of my head an add-on that handles subclaims (when you remove subclaims) will want to intercept rather than undo, etc.

**Comment by Jikoo** [comment]
Right, yeah, GP should be listening to its events at highest or monitor so addons have the opportunity to intercept. I wrote that up initially, but sleepy me having just woken up mixed my logic, assumed I was incorrect, and deleted it. The priorities really are terribly named.

**Comment by RoboMWM** [comment]
Well the idea for having GP listen to its own events at lowest priority is moreso to reflect what would happen in a non-custom-event sort of deal (blockbreakevent being canceled), and addons can react to GP canceling an action. This is only for handling bukkit's events in regards to actual protection of claims though - things like ClaimCreateEvent and WandEvent will still be their own events separate from this package and fired normally within GP's processing, just like PreventPvP and DeleteClaim are. So that would cover your use case with handling subclaims.

That being said, there might be times I suppose when a plugin really does want to prevent GP from deciding to take action in the first place (though I can't think of any use case right now), so I suppose I'll have GP listen to its own "BukkitToGP" events at low priority.

---
As for the bukkit listeners, don't know if I should have them listen at lowest or low priority. Not sure what the conventions of other plugins that cancel such actions to provide functionality (other than claim protection), being that they likely don't listen at lowest priority anyways. I guess for now I'll listen at lowest and see how that goes.

**Comment by RoboMWM** [comment]
So, probably will have GP's listeners listen to its own events at normal priority. I don't see any reason to worry about priority to much when GP is listening to itself.

However, not sure if I should just fire one single custom event with a method to determine the "type", or different events (e.g. GPFarmEvent for animals and crops, GPAlterEvent for item frames, armor stands), since they all seem to have a similar structure (source, target)

See: https://github.com/TechFortress/GriefPrevention/tree/dev/src/me/ryanhamshire/GriefPrevention/events/custom

**Comment by RoboMWM** [comment]
@frozenbeard

**Comment by caxerx** [comment]
I don't sure it help or not, but Sponge version of Grief Prevention had refactor the plugin with separate api and plugin part. Also added Claim Create and Resize event.
https://github.com/MinecraftPortCentral/GriefPrevention

**Comment by RoboMWM** [comment]
I'm actually interested in de-bloating this plugin to reduce future bugs and confusion, as well as encouraging contribution (in the form of addons). Thanks for the hyperlink though.

**Comment by FrozenBeard** [comment]
@RoboMWM As someone that has used GriefPrevention since Tux2 created it and used every iteration, Can I request that we keep the data schema for Acquired Blocks and Bonus Blocks, the ideology where figuring out someone's claim blocks based on the claims they have is a very smart one. I really don't want to see the plugin simplified to the point where data is actually getting removed from the players claim count in the database, it should only increment. This avoids loss of data when inevitable bugs appear and was designed specifically to be strong.

Will the database schema stay the same? 100% of the issues from doing a large update from other plugins is always the developer never considering the upgrade process from years of use, and is always my first thought when people say a whole recode is happening.

Thanks.

**Comment by RoboMWM** [comment]
> Can I request that we keep the data schema for Acquired Blocks and Bonus Blocks
The current method? Or are you suggesting a change?

> Will the database schema stay the same? 
I'm thinking of offhanding storage methods to addons - still not entirely sure on how this is going to go, but I'd like data to also be shared via events, so anyone can implement any data storage type they so wish to use. If it changes, I'll implement a converter (idk if I want to bloat the plugin with a converter - but perhaps I might have to do that for the first couple of versions for those who don't read), **if** it changes. 

However, I'm not planning to add anything new per se, so I doubt that this refactor will require any data schema changes. If anything, the only thing that I'd change is removing the player's last login time, since that's stored by the server.

**Comment by FrozenBeard** [comment]
@RoboMWM Im suggesting we keep Tux2's original ideology of how claims are saved for claimblocks so that the amount of "claim blocks" people have is generated dynamically based on the claims they have in the world and not just the number in the database. This is my only concern as I don't want GP to move to deducting claimblocks from a players database, this would be bad! I'm sure you won't! I thought I best just speak my mind as its something that I was worried about.  There was a brief time when /acb didn't add to the bonus blocks but directly was put into Acquired, which really screwed up my data, it was fixed, but it was a big mistake that cost me hours to fix after it was patched.

**Comment by RoboMWM** [comment]
So just had an idea regarding claim IDs: instead of storing and incrementing a number, how about we just use `System#currentTimeMillis`? With one obvious issue being if more than one claim is created at the exact same instant (easy to fix via checking against the last-used claim ID and adding 1 to that), **are there any other potential issues with this?**

The only other "issue" I see is there wouldn't be any memorable "global" id to print to users (a la #126), but that's about it.

**Comment by caxerx** [comment]
Is that the claim id must be number? if not, seems generate a uuid may be a better way.

**Comment by RoboMWM** [comment]
Why would a UUID be better, wouldn't that just take up more space?

**Comment by caxerx** [comment]
UUID is hard to conflict even merge with other server. So I think it will avoid potential problem and unnecessary duplicate check.

**Comment by RoboMWM** [comment]
I've never ever seen a server "merge" and attempt to merge claim data; so I suppose this is a valid point but I see this as a scenario that would never happen. (And if it does, it'd be easy to make an offline tool to resolve such conflicts.) This argument is mostly feasible against the existing system, however. Using just a timestamp, a claim would have to be created on both servers at the exact same time (to the millisecond) for such a conflict to occur.

Either way, a "UUID" still has to be generated from something, and keep in mind that all claims have to be loaded in memory when the server is online.

**Comment by RoboMWM** [comment]
Alright, came across a couple questions to throw at some of you who are server admins:

1. Should /accesstrust be removed? Seeing how little /accesstrust grants, and mostly everyone on my server who actually uses that permission level generally grants it to the public; I have yet to see a need where a specific set of players should have _only_ access to fences, buttons, levers, and nothing else. It would make sense to just include wood fences and buttons (along with wood doors and all pressure plates, as is currently the case with the default config in 16.x) to be accessible to the public, folding stone buttons and levers into the /containertrust permission. https://www.strawpoll.me/15962254

2. Should fires that **started inside a claim** spread and burn within that claim? A lot of my players aren't actually aware that the fireplace they just made doesn't pass the minecraft building inspection for fire safety. However, since GP disables _all_ firespread and burning within a claim (with exception of netherrack), my players usually are never aware of this. I'd like to promote a more vanilla-like environment, especially with something like this, but it's really up to you guys to decide if this is something that should be included in GP by default since this would be a potentially devastating change from version 16.x. https://www.strawpoll.me/15962260

**Comment by weaves7** [comment]
Thanks for asking.
1. I really need to have /accesstrust since I made a plugin that hooks into GP and checks if a player has access trust in a claim. And if they do they are allowed to fly in it. Otherwise they are not allowed to fly. They can of course fly if they have even more access to the claim like being the owner or have /trust. Access trust lets a claim owner give someone permission to fly and look around their build without being able to open chests and such.
2. Preventing fire spread started in a claim should be kept. Main reason is all the servers that have lots of builds without regard to fire safety that will go up in smoke with an update. So many players have become accustom to building these non fire safe builds knowing that GP will save them from griefing themselves (even if they don't know its GP specifically doing it). An option to turn it off or on would be fine or if a fire spread module that could be added, could also work as long as there was a way to prevent the fire spread during an update.

**Comment by FrozenBeard** [comment]
Thanks for asking.

1. Keep /accesstrust. Some of the larger groups of players that have Crews for people to join have certain jobs for brand new people that don't want to trust yet, like building and accessing building material without being able to do much else, so they make sub-claims for them to build and they have storage rooms that they can only access and not break/build, they have some chests blocked off with blocks so they cant be accessed. Saves having multiple storage rooms.

2. Keep it off as default, I would be here forever listing the amount of issues that would cause. BUT create a toggle for it, like /claimexplosions, in the rare occurrence they do want to burn a ton of trees down have something like /claimfirespread. What would be nice is more control over who in the claim can toggle these things, I have had to deal with people in /trust blowing up a base out of spite to then have people not understand that trusted people can toggle it!

**Comment by Jikoo** [comment]
1. Users often grant `/accesstrust` to claims that are meant to be explorable - showing off a build, things of that nature. Thanks to `/restrictsubclaim` this should be much more easily replicated in a different manner, but it's a lot easier to not force my more dedicated users to revisit (and re-learn) all their claim logic.
2. I'd love for fire spread to be a thing for those authorized to start fires, but if fire tracking is too much of a nightmare, I'd give it a miss.

**Comment by RoboMWM** [comment]
Thanks for the feedback! I'll wait a bit more for others to get a chance to reply, but I'll go ahead and respond to a few right now.

>  since I made a plugin that hooks into GP and checks if a player has access trust in a claim. And if they do they are allowed to fly in it. 

Honestly sounds like something you can bake in your plugin. [Assuming it's removed,] just use the now-defunct /accesstrust as an alias to store who can fly in a claim. This also sounds like /accesstrust is being used as a flag (and in fact there is a flag for flying in GriefPrevention Flags), so I consider this addon-territory.

>  like building and accessing building material without being able to do much else, so they make sub-claims for them to build and they have storage rooms that they can only access and not break/build, they have some chests blocked off with blocks so they cant be accessed. Saves having multiple storage rooms.

Sound like /containertrust is what they're using, especially since they're using blocks to restrict who can open which chests while giving "free" chest access to others. /accesstrust doesn't give any container access at all.

> Is there a discord server for all GP related re-factoring?

Link in OP.

> Users often grant /accesstrust to claims that are meant to be explorable - showing off a build, things of that nature.

Which is exactly what most people do - they perform `/accesstrust public`. Making additional things like wood buttons and fences public by default saves from having to do this.

**Comment by RoboMWM** [comment]
> but if fire tracking is too much of a nightmare, I'd give it a miss.

It'd be more of "is the source block also within the claim?" when determining if the fire started within the claim.

> BUT create a toggle for it, like /claimexplosions

That's what will be included in that toggle (will be more of a "/naturalgrief"-esque sort of command) if I don't make the proposed change.

> So many players have become accustom to building these non fire safe builds knowing that GP will save them from griefing themselves (even if they don't know its GP specifically doing it).

Also my thoughts, but at the same time I really want to enforce more vanilla rules - especially if they mess up a claim resize or GP somehow gets borked on a server start/update. That or perhaps upon starting a fire GP could warn the user about it not being a safe area via checking the surroundings... hmm, maybe it could do that and put out the fire/cancel the fire ignition, and force the user to run /allowunsafefires or something like that to create said fire.

**Comment by ShaneBeee** [comment]
I just voted but i wanted to give my feedback on why i voted such ways.

Access trust:
I say leave it since its been a thing for a long time, why take it out now? I get where you are coming from, it is rarely used, BUT.... there may be certain instances a player may want to give someone access to their claim but NOT to their chests.

Fire Spread:
I voted to leave it the way it is.. Here is why. Let's say me, player A has a claim, and I have given my friend player B /trust to my claim. Now, let's say in offline and B is a jerk and sets fire to a block, it would then spread and have the possibility to burn down my whole claim. I feel like that goes against the "prevention of grief" and could therefor be used as a way to grief players. ALSO, I know myself I have built fireplaces several times that go against MineCraft's fire regulations and I'm thankful that GP stops the fire spread, so If you were to take it out, I would have a few burning houses on my hands ;) and this would most likely be true for a lot of players. Let's say you did change it, and I updated on my server, and several players had fire places..... after said update there could be a lot of chaos with a lot of potential house fires.
Again, I totally get your point on this, because I agree with giving players the vanilla experience and having to build properly, BUT I feel that this could turn into a major issue with griefing players

**Comment by RoboMWM** [comment]
>  Let's say me, player A has a claim, and I have given my friend player B /trust to my claim. 

I've also thought about this, but the only difference here vs. manually breaking blocks is the amount of time required to cause such grief. Either way, the player will be able to accomplish their goal if given /trust, firespread or not.

**Comment by ShaneBeee** [comment]
Ah very valid point.... 
Ok well I vote for toggle able or an option in the config maybe? Let the server admins choose. I feel 50/50 on the fire issue as I do agree to push players to build vanilla style with fire regulations, but I also fear the stupid players who "But I didn't know fire would spread and my whole house burned down".... like others and myself have said, especially in an instance where the server admins update GP.... and now any house with a fireplace or fire decoration, have the potential for a huge fire and/or accidentally griefing themselves.

**Comment by weaves7** [comment]
>Honestly sounds like something you can >bake in your plugin. [Assuming it's >removed,] just use the now-defunct >/accesstrust as an alias to store who can >fly in a claim. This also sounds like >/accesstrust is being used as a flag (and >in fact there is a flag for flying in >GriefPrevention Flags), so I consider this >addon-territory.
You are correct  that I could bake this in. But It's more than just a flag. The plugin does other flight checks I didn't mention. My plugin and server is not that big of a deal since I can code accordingly. But for others, say you are a player with a shop in the middle of nowhere with a warp to it and a perimeter wall with an iron door to the outside. This prevents just anyone from warping there and going outside the claim and building an eyesore. But say another player that you know makes cool builds wants to build nearby and be able to just come and go from the shop. You give them access trust so they can open the door  or fly over the wall but not be able to open chests.

**Comment by FrozenBeard** [comment]
> Sound like /containertrust is what they're using, especially since they're using blocks to restrict who can open which chests while giving "free" chest access to others. /accesstrust doesn't give any container access at all.

Completely the opposite, We do not have chests "locked" on PirateCraft as you can put a physical block over a chest to "lock" it if its claimed, this has worked wonders, as people who forget to put a block over chests can have their stuff looted. So /containertrust is the command we never use, as there is literally no point to it if you disable locks on chests, the lock system is pointless if people place blocks on top of their chests. We have people create ingenious piston based vaults, where they trigger locking/unlocking their chests via redstone, which also ties in with our shop plugin that allows activating redstone via a sign shop :) 
/accesstrust is used for buttons to gain access, Wooden doors allow entry to everyone, Iron doors do not. So they need a button and they can control access easily.

**Comment by RoboMWM** [comment]
> Completely the opposite, We do not have chests "locked" on PirateCraft as you can put a physical block over a chest to "lock" it if its claimed, this has worked wonders, as people who forget to put a block over chests can have their stuff looted. 

In that case, giving /accesstrust is the equivalent of giving /containertrust on your server since you have allowTheft enabled.

**Comment by voretaq7** [comment]
Re: fire spread, I'm inclined to keep it the way it is (no fire spread in claims by default) & voted that way, but in terms of the vanilla experience & building requirements I see the logic the other way.

How hard/server-intensive would it be to make this a per-claim option that the owner can toggle (defaulting to current behavior on existing claims)? That seems a reasonable compromise to me.


Re: /accesstrust, I'm in favor of keeping it. We use it on my server as a convenient way of letting someone into our builds to wander around, and the ability to not grant access to fences helps for folks with outdoor farms/pens (less risk of someone wandering through and leaving your fence open so your livestock wanders).

I'm definitely against folding /accesstrust functionality into /containertrust: These are fundamentally different rights. I might /accesstrust everyone so they can come into my home to seek shelter from a zombie & wander around looking at the decor, but I DON'T want them rummaging through the chests in my store room. That's ***MY*** chest of lapis, and it wasn't easy to fill! :)

**Comment by RoboMWM** [comment]
Accesstrust is already included in containertrust, if that's what you meant. If not, the idea is that _in addition to_ wood doors which can be opened (by default), fences would be also openable, by default, thus basically eliminating the need for accesstrust in the first place.

**Comment by voretaq7** [comment]
Well what I actually meant was to take accesstrust out of containertrust since they should (IMHO) be severable: I should be able to let you look in my boxes or operate my redstone devices independently, but I'm also fine with keeping things the way they are because I'm probably in the minority on wanting that fine a permission structure.

I could go either way on fences being openable by default as long as we can still lock them via the config file, but losing the ability to grant just redstone (button/lever) and door/fence access would hurt: I'd be doing a lot of subdividing to protect storage areas in otherwise-public builds where people need to be able to hit (stone) buttons to open the doors & come in.

 An alternate option would be to give accesstrust to the public by default (probably what most folks want to do) & let people revoke it if necessary to make a private claim.

**Comment by RoboMWM** [comment]
Permissions are currently a hierarchy, which makes it easy (build and break should have containertrust and accesstrust for example). They don't act as separate flags.

**Comment by RoboMWM** [comment]
Went ahead and decided to preserve /accesstrust, and is controlled via `GPToggleBlockStateEvent`. Probably will fold fire damage along with the /claimexplosions command.

Anyways, branch dev/v20 can now be compiled and run. Functionality is very barebones - currently no indication of claim borders or the like, but they can be created. If you want, you can test out its file saving and such - but I'm primarily looking for feedback on the API as of now. Is it sufficient?

ClaimClerk - a getter for this will exist in the main class, and provides access to GP's stored claims. It provides caching via requiring a Player object to be passed (though it also caches on the null key) on `#getClaim`

FlatFileStorage - playerdata and claimdata saves are done asynchronously and have a thread pool for each - any problems with thread safety/design here?

And of course, any other comments regarding any particular design/organization/etc.

**Comment by RoboMWM** [comment]
https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/21453583/artifacts

**Comment by RoboMWM** [comment]
Alpha 2 download: https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/21511712/artifacts

New things in alpha 2:
- Fixed visualization appearing at y=0
- More visualization updates (overlap on resizing and creating, abandoning claims clearing visualization)
- Added resize functionality to claimtool
- Placeholder messages
  - resizing
  - error messages for attempting to create claim within an existing claim
- Lots of other internal stuff

Note that when I release a new alpha build, I have not yet tested it (other than it compiling). So your feedback for alpha builds is desirable! I'll usually start testing alpha builds some time after an alpha release, make more changes, then implement more things for another alpha release.

**Comment by Jikoo** [comment]
Noticed you doing some config work and remembered a couple old frustrations. I dislike GP's use of semicolons as list separators in config options, so I'm hoping v20 will migrate to actually using YAML lists.

As a server owner I was also annoyed at having to seek out every alias of a command to block. For example, if you are using Essentials' homes feature, to block /sethome in claims your CommandsRequiringAccessTrust must include `/sethome;/esethome;/createhome;/ecreatehome;/essentials:sethome;/essentials:esethome;/essentials:createhome;/essentials:ecreatehome`. It would be great to block a single command or alias and just not have to worry about it, though unfortunately I'm not aware of a convenient way to do this without either grabbing the server's CommandMap or iterating every command of every plugin.

**Comment by RoboMWM** [comment]
Re blocking commands, I know Big_Scary implemented something of the sort with PhantomAdmin. https://github.com/BigScary/PhantomAdmin

Re config, trying to find a good way to simply add a single line of code for each new config option. Although nested enums are a thing, I don't know of any way to use the constructor from the outer enum. I think I came up with an idea earlier today...

**Comment by FrozenBeard** [comment]
Is v20 still going to happen? What are the issues that you're stuck on? I keep having users request a siege re-make but we were kind of waiting until V20.
We've Been experimenting with the idea of putting people into adventure mode when they enter a claim to stop all the issues with griefprevntion where people can just spam break blocks until they can bypass, like iron doors, maybe this could be considered for v20 to prevent these annoyances.

**Comment by RoboMWM** [comment]
v20 is happening, a couple commits were made recently. Still a lot of work (hours) not to just reimplement but also design properly. And that doesn't even include testing.

**Comment by SrBedrock** [comment]
I can help you test if you need to!

**Comment by RoboMWM** [comment]
Work for v20 is being organized on a [GitHub projects board](https://github.com/TechFortress/GriefPrevention/projects/1)

**Comment by RoboMWM** [comment]
@FrozenBeard 

> where people can just spam break blocks until they can bypass, like iron doors,

This has been fixed several months ago, if you're talking about during a siege

**Comment by FrozenBeard** [comment]
@RoboMWM just in general, people "glitch" through blocks into peoples claims by just spam breaking the block over and over until they pop themselves in, its always been a bit of an issue, they usually use thin blocks like iron doors, I have a video somewhere.
We were thinking about if you were not trusted putting that person into adventure mode inside that claim so they couldn't even spam break blocks until they glitched to get through.

**Comment by RoboMWM** [comment]
In case anyone was curious why we're doing this: https://codeclimate.com/github/TechFortress/GriefPrevention

![](https://i.imgur.com/pUxIlU0.png)

**Comment by RoboMWM** [comment]
v20 has been going along for quite some time, and I pushed a couple updates today. Considering all the work that has gone into this, I'm thinking it may be a better approach to slowly migrate GP itself over to look something like this, instead of doing a full-on replace. There is a lot to implement, and nobody has tested (or at least provided any feedback).

I'm looking for feedback on this, but here's one idea of how it could go:

I'd start with non-impactful backend refactors. Mostly just code cleanup such as breaking massive classes into smaller classes, implementing the GP events and "funnel" system, etc. The current state of the dev/v20 branch will basically be used as the blueprint for this step.

Then I'd move into more major changes, e.g. modifying the database interface, modifying the config, removing hardly-used features, etc. I'm thinking at this point I'd need to break off into a v20 branch and publish betas due to the feature removal - but one way or another, I'm thinking we'll need a hard break from the less-used features; I don't think it'll be worth the time to constantly be writing migration functions to preserve the configuration settings for these features.

Lastly, after the codebase is mostly clean and contained, there will be a major focus on re-adding removed features or exposing parts of GP that make it easy to add these features back as addons.

**Comment by Jikoo** [comment]
My two cents for a roadmap:

1. Code style refactor. Consistency makes contribution easier. Possibly provide autoformatter settings for IDEs to speed things along even more.
2. Code health refactor. We just got burned by deprecation suppression, would like to see a pass over the whole plugin for common causes of issues. GP is a mess of easily resolvable warnings.
3. Non-breaking API changes - split up large classes, reduce duplicate code, break down long methods.
   1. Determine which current GP features are and are not desirable core features (i.e. siege, restorenature, etc.) and migrate them to addons, providing additional events/new API following v20 design as necessary.
4. Breaking changes to existing API. Delete outdated methods and classes, a full v20 clean house.
6. Infinity and beyond! Determine whether or not it is possible to create addons from requests and add API/events for developers where necessary.

Definitely agree that a more gradual change would make the move to v20 more achievable. Small steps are manageable, one big jump is very taxing.

**Comment by RoboMWM** [comment]
> Possibly provide autoformatter settings for IDEs to speed things along even more.

Anything on this? I see some stuff about exporting formatter settings to .xml but not sure how I'd make it auto-import as well.

**Comment by Muspah** [comment]
The most basic and easiest addition would be a .editorconfig file.

**Comment by Jikoo** [comment]
> Anything on this? I see some stuff about exporting formatter settings to .xml but not sure how I'd make it auto-import as well.

IntelliJ should automatically apply a provided .editorconfig to the directory containing it, including subfolders. You can choose that specifically when exporting.
![image](https://user-images.githubusercontent.com/1353270/84031043-fe815780-a962-11ea-8019-e934872e7897.png)

I believe Eclipse can only share formatter settings either via manual setup from provided XML or by sharing entire project setup (.project, .classpath) and using a managed configuration but I could be wrong - never really had reason to look into it before I swapped software.

**Comment by RoboMWM** [comment]
Thanks! Possible to validate any of this via AppVeyor? (I'd be ok with another CI or service to validate - which may be more appropriate since code that can be compiled should pass, I guess? But otherwise, would be much easier to add to appveyor and avoids me having to add yet another service with permissions to repos.)

**Comment by Muspah** [comment]
Checkstyle should be able to check this (and many more) rules with a maven plug-in on compile time.

**Comment by RoboMWM** [comment]
I thought /gpblockinfo was removed.

Not sure if I'd worry about annotations right now.

**Comment by Jikoo** [comment]
The code's still there. I didn't check to see if it was declared in the plugin.yml.

The reason I'm doing the annotations is that every time I try to work with the code I end up having to bounce all over trying to see whether or not a particular parameter is allowed to be null. BigScary usually did an okay job of commenting (not documenting though, unfortunately) but it could be a lot better. The Annotations artifact doesn't need to be shaded or anything, no file size increase. This is pure QoL for developers looking to work with GP in any context.

**Comment by RoboMWM** [comment]
Ok, that's fine then. I know I tried messing around with annotations a few times, I think one of them is named similar but imports a dependency that's outside of whichever one is included with spigot/paper.

**Comment by Jikoo** [comment]
How do you feel about Metadatable vs PersistentDataContainer? I personally would like to see GP move to PDC.

Pros:
* Persistent (wow)
  - Currently GP loses track of falling blocks/portal-trapped players/etc. on restart
* (incredibly slightly) More efficient
  - PDC does not consume memory when unloaded
  - Metadatable keeps data loaded until manually removed or server is shut down
  - Theoretically roughly the same performance? Not 100% on this. I know all entity metadata is (eventually) shoved into a Map<ID, Object> where ID is worldname:objectid, but I haven't looked through the entire PDC flow. I believe it's essentially the same thing, just per-entity piggybacking the existing NBT system.

Cons:
* Can't store literally any object quite so easily
  - Can store UUID/Location still, but requires additional handling (which I am willing to write)
* Persists even if GP is removed from the server

Either way I would like to unify all metadata usage into some sort of cohesive utility. Some of it is pretty messy and a lot of it is unnecessarily complex. It could also be used to simplify ownership tracking, which would in turn simplify projectile handling and probably slightly increase performance.

**Comment by RoboMWM** [comment]
A quick search reveals that persistentdatacontainer is new (since 1.14)? Interesting.

Other than tagging falling entities, I'm not sure where else GP really necessitates the need to tag items, other than the PRs you've made. So ya it's fine to use that.

**Comment by brasilcraft54** [comment]
allow wither to kill animals this would help make rose farm of whiter in 1.16.
