### ISSUE TITLE
Language (translation) support

### ISSUE THREAD

**Issue by Madis0** [TechFortress/GriefPrevention#705]
**As** a player
**I want** to read GriefPrevention messages in my language
**Because** I may not understand English that well.

Therefore, I suggest adding full language support to GriefPrevention, so it would be possible to add languages upstream (by commiting to this repo) and activating on the server by simply setting the locale in config.

Also, it would be nice to [allow user-made subtitles](https://support.google.com/youtube/answer/6054623?hl=en) [on the instruction video](https://www.youtube.com/watch?v=VDsjXB-BaE0).

**Comment by RoboMWM** [comment]
It's not my instruction video so I can't do that. Might do something for v20 - but you can put anything you want there, so it can be other text instructions (like I do on my server) or your own video.

People are free to submit translations either here or in spigot and I'll add it to the wiki. Nobody seems to have done that though despite a few (before I became the maintainer) who have translated the file before. (I used to allow editing until idiots constantly did random edits to it.)

**Comment by Madis0** [comment]
> People are free to submit translations either here or in spigot and I'll add it to the wiki.

Well, why wiki? Why not have separate strings files for different languages, like many other plugins do? That would make it easier for administrators to apply them, too.

**Comment by RoboMWM** [comment]
> Why not have separate strings files for different languages,

I'm sorry, I don't know what you're asking for. 

I personally modify the messages.yml just to change the wording or to remove messages. I'm not interested in hard-coding language values - the messages can be edited like most other mature plugins.

**Comment by RoboMWM** [comment]
The only reasonable suggestion I can make from that is that you want the plugin to come with a bunch of already-translated files. I'm opposed to that for two reasons:

- clutter in the folder (less simple)
- I don't have a translation team

**Comment by RoboMWM** [comment]
I believe there are translation services out there, like transifex (and some other one that I don't recall). I think I tried setting up one but never really played much with it - idk if it's public so others can see it or not.

**Comment by Madis0** [comment]
> The only reasonable suggestion I can make from that is that you want the plugin to come with a bunch of already-translated files. I'm opposed to that for two reasons:
> 
>     * clutter in the folder (less simple)
> 
>     * I don't have a translation team

Yes, that's what I'm asking for. Clutter in the folder is negligible (you could download the locale on server start) and translation team is not necessary due to crowd-sourcing.

 > I believe there are translation services out there, like transifex (and some other one that I don't recall). I think I tried setting up one but never really played much with it - idk if it's public so others can see it or not.

I assume you mean Transifex and Crowdin - I use both for various projects but prefer the latter. Both also give free plans for FOSS projects. Whether it is public (freely joinable) or private (invitation-based) is up to you, in the settings.
But you don't have to sign up for either, you can continue using GitHub and just merge pull requests as they come.

Here are some popular examples of managing languages:

- [EssentialsX](https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src) [(now using Crowdin for uploads)](https://crowdin.com/project/essentialsx-official)
- [Jobs](https://github.com/Zrips/Jobs/tree/master/src/main/resources/locale)
- [Modern LWC](https://github.com/Tsuser1/Modern-LWC/tree/master/src/lang)

**Comment by Dum4G** [comment]
Any status on that suggestion? @RoboMWM  In case folder cluttering matters you can follow the opeNLogin approach where
config.yml lets you choose the language and points where to download translations from:

# Language of the plugin.
# For more information: https://github.com/nickuc/OpeNLogin/blob/master/docs/lang.md
languageFile: 'messages_en.yml'


Your community are your translation team and proofreaders
