### ISSUE TITLE
How to change the color,format and or look of the size of a claim.

### ISSUE THREAD

**Issue by XenZify** [TechFortress/GriefPrevention#722]
How can I change how this blue number looks when using a Stick to view a claim?
![image](https://user-images.githubusercontent.com/60237755/74736596-223c5880-5221-11ea-9220-13257130b790.png)
I've tried adding $6 after the period that's after the player's name placeholder, but it doesn't work.

**Comment by XenZify** [comment]
Someone help, please? It's really bugging me!

**Comment by XenZify** [comment]
@RoboMWM Please get back to me?

**Comment by Jikoo** [comment]
Please be patient. People have lives and concerns outside of Minecraft. The color of some text is not an urgent and gamebreaking issue. Everyone watching issues gets a notification when an issue is updated, spamming will only cause irritation.

As for your question, I don't know, I'd have to look through the code to see what gets sent. Unfortunately, I don't have time right now.

**Comment by RoboMWM** [comment]
Calculation is done internally afaik, so not configurable. Will be configurable in v20. Unsure if an addon can adjust.

**Comment by XenZify** [comment]
Is there any ETA on the v20?

**Comment by XenZify** [comment]
> Is there any ETA on the v20?

@RoboMWM ?? I waited for 22days...

**Comment by RoboMWM** [comment]
#63 

> I waited for 22days...

What contract did I sign?

**Comment by XenZify** [comment]
> See #63 for v20 information... it's pinned.
> 
> > I waited for 22days...
> 
> What contract did I sign?

You don't need to be a cunt, I was told not to ping because yall would get back to me and I patiently wait and in return got 0 replies... :( I'm sorry!

**Comment by XenZify** [comment]
It would also be nice to have the ability to change the color of the link to the claiming tutorial. OR and change the link as there's better quick tutorials out there! <3

**Comment by bigpresh** [comment]
Definitely good suggestions, and something that will likely be possible in GP v20.  However, v20 is a *big* bit of work with a huge refactor of a fairly messy codebase at present, and being done by a volunteer when time permits as opposed to full-time employees working on it, so (a) no ETAs are really available, (b) it *will* take some time.

I can't speak for @RoboMWM as to whether it would definitely be accepted, but I'd imagine that if someone wanted to raise a pull request to make the message formatting configurable (and/or to make the claiming tutorial video URL configurable) in the current GP it may well be accepted, but is unlikely to be done by the current team when that effort could be spent on v20 instead.

**Comment by XenZify** [comment]
> Definitely good suggestions, and something that will likely be possible in GP v20. However, v20 is a _big_ bit of work with a huge refactor of a fairly messy codebase at present, and being done by a volunteer when time permits as opposed to full-time employees working on it, so (a) no ETAs are really available, (b) it _will_ take some time.
> 
> I can't speak for @RoboMWM as to whether it would definitely be accepted, but I'd imagine that if someone wanted to raise a pull request to make the message formatting configurable (and/or to make the claiming tutorial video URL configurable) in the current GP it may well be accepted, but is unlikely to be done by the current team when that effort could be spent on v20 instead.

Why wouldn't it be done as 90% of servers using this plugin have specific color formats... and that's something that sticks out on every single one of them!

**Comment by Jikoo** [comment]
> Why wouldn't it be done as 90% of servers using this plugin have specific color formats... and that's something that sticks out on every single one of them!

>The color of some text is not an urgent and gamebreaking issue.

Why waste development time on code that you're planning to delete? Feel free to submit a pull request or put up some cash if it's bothering you that much.

I've had about five goes at this next section. Please pardon how impolitely phrased it is, goodness knows I've tried.

 You're getting a decent quality plugin for free, maintained for free mostly by Robo. You have proceeded to insult Robo for not responding to your demands. How likely do you think it is that Robo is going to pay attention to your wants? If I were to insult you and then throw a little heart in my next message, would that make it okay? When you look through the issue tracker and see problems with GP that affect gameplay mechanics, what makes you think that this issue is a better use of Robo's time?

**Comment by XenZify** [comment]
Fuck off faggot
