### ISSUE TITLE
FAQ - Check this first before submitting a bug report/question!

### ISSUE THREAD

**Issue by RoboMWM** [TechFortress/GriefPrevention#752]
<details>
<summary><b>Before submitting a bug report, try these things</b></summary>

- [ ] Does the issue still occur if GriefPrevention is the only plugin running?
</details>

<details>
<summary><b>Pressure Plates can be activated/Wooden Buttons can be pressed with Arrows!</b></summary>

This is by design. To protect buttons, use stone buttons instead - these _cannot_ be depressed by arrows.

https://www.spigotmc.org/threads/griefprevention.35615/page-31#post-728722

> Players like to use pressure plates with monsters and dropped items, so turning those activators off would be creating a problem by taking away game elements players really enjoy. As long as they're on, any player who I stop from directly activating a plate by standing on it can use either of those as a workaround. Similarly for wooden buttons (arrows). So I allow them outright because otherwise players would get a false sense of security, then feel violated when a clever griefer uses a workaround.

https://www.spigotmc.org/threads/griefprevention.35615/page-19#post-567357

> There's no option to lock pressure plates. Lots of players like to have an option to activate redstone with monsters (monster grinders) or items. If you were to lock them all over your server, those gameplay elements wouldn't be available. So buttons/levers are lockable while touchplates are not - this gives players options so they can create their own exemptions to access rules without having to subdivide their land claims. For example having a door that the public can open (touchplate) and another that only their friends can activate (button/lever). Also monsters and items will never have permission to do anything in a land claim, so by using touchplates, players can let monsters and items activate traps and other gadgets.

Additionally, it is not technically feasible to determine the projectile that pushed the button - see this comment by Jikoo: https://github.com/TechFortress/GriefPrevention/issues/647#issuecomment-544924873

> Wooden button usage by projectiles is actually not possible to directly detect via Spigot's API, you have to guess based on which entities are nearby. It becomes a mess - under what circumstances do we block access by other entities?
</details>
<details>
<summary><strong>Claims owned by inactive players aren't expiring!</strong></summary>

The inactive claims check runs very slowly. It has been improved recently but it is still intentionally slow to avoid any performance impact to the server. If you want this check to run faster, modify the `Advanced.ClaimExpirationCheckRate` config node at your own risk.

https://www.spigotmc.org/threads/griefprevention.35615/page-31#post-728722

> It's slow to work, because I want to keep the CPU cost down. About once per minute, GP looks at one land claim to see if it has expired. Slowly over time, old claims from inactive players will disappear.

Note: The method has been modified to now look at a single claim _owner_ per minute instead of a single claim.
</details>

<details>
<summary><b>How do I remove a message from messages.yml?</b></summary>

Simply modify the line to contain only a blank string, and GP will ignore printing the line. Use two quotes (single or double quotes). E.g.

```yml
  IgnoringClaims:
    Text: ""
```
</details>

<details>
<summary><b>Players are not receiving claim blocks!</b></summary>

AFK players do not receive claim blocks (unless configured in the `Advanced` section of the config). Enable debug logs in the GP config to see information about accrued claimblock deliveries, which occur every 10 minutes.
</details>

**Comment by RoboMWM** [comment]
#### Common feature requests

- [Can you enforce a minimum distance between claims?](124)

**Comment by RoboMWM** [comment]
If you would like to add an entry here, please comment with the question and answer below! Please use the following format:
```html
<details>
<summary><b>Question goes here</b></summary>

Answer goes here
</details>
```

**Comment by RoboMWM** [comment]
Reserved

**Comment by jonesman103** [comment]
hey: I have a problem. people on my server can not open doors unless they have op.

**Comment by Runred** [comment]
Adding the possibility to rename claims and showing the name with /claimlist?

**Comment by botta96** [comment]
Hi, I use this plugin for my survival server, think about creating VIP packages with the possibility of creating larger complaints, how can I do? I have tried in several ways but I cannot provide the creation of claims larger than the standard format inserted in the configuration file Thanks

**Comment by RoboMWM** [comment]
Please note that comments here are only for submitting FAQs to the list! See this post for the template: https://github.com/TechFortress/GriefPrevention/issues/752#issuecomment-599151463

(I.e. don't make me lock this issue cuz ppl can't read)

**Comment by RoboMWM** [comment]
test

**Comment by RoboMWM** [comment]
- Added entry `/claimexplosions does not persist when the claim owner logs off/server restarts`

**Comment by Robomnz** [comment]
![image](https://user-images.githubusercontent.com/34904608/92544125-37520500-f2a1-11ea-8efd-30bf630477ae.png)
i did /containertrust public on a admin claim and i could not access any of the chests/barrels/enchantment tables, furnaces or even anvils, im using the latest grief prevention version 16.14.0 and running a 1.16.2 server is this a bug?

**Comment by Jikoo** [comment]
That message is not from GriefPrevention. If memory serves, that's from EssentialsProtect.

**Comment by Robomnz** [comment]
ah ok lemme remove that real quick and see if that fixes it

**Comment by Robomnz** [comment]
![image](https://user-images.githubusercontent.com/34904608/92545549-7f265b80-f2a4-11ea-9b1d-c180580f67f6.png)

**Comment by Jikoo** [comment]
Again, those messages are not from GP. Also, if you're having in issue, please open an issue instead of posting here. Please make sure you restarted your server after removing EssentialsProtect.

**Comment by Robomnz** [comment]
i did reboot my server after removing it and the issue is still there

**Comment by RoboMWM** [comment]
Some people really can't be bothered to read anything can they.

**Comment by Saltymexican** [comment]
![image](https://user-images.githubusercontent.com/52759884/94318476-f3414e80-ff88-11ea-9c64-44736772d505.png)
Is there a way to put the number of claim blocs we have in the tab ? i use the TAB plugin

**Comment by RoboMWM** [comment]
Gonna lock this since nobody has contributed to the FAQ and I'm making a documentation website repo elsewhere that should replace this.
