### ISSUE TITLE
Hello, how do you give players claim blocks? (not over time / accrued)

### ISSUE THREAD

**Issue by FauxOW** [TechFortress/GriefPrevention#804]
The answer to your question may exist in the wiki, go check that out first! 

Wiki: https://github.com/TechFortress/GriefPrevention/wiki

Otherwise, if you have a spigot account, you may have better luck posting in the discussion thread so people who follow the thread may see your question. https://www.spigotmc.org/threads/griefprevention.35615/page-311

Still no luck? Really? Then go ahead and ask here.

**Comment by RoboMWM** [comment]
Well, did you check the wiki?

**Comment by Jikoo** [comment]
You can configure the amount of blocks that players get when starting in your configuration. If you want to give them more later, there are [admin commands](https://github.com/TechFortress/GriefPrevention/wiki/Commands#admin-commands) for adding bonus blocks or changing base blocks for players.
