### ISSUE TITLE
Dynmap support ?

### ISSUE THREAD

**Issue by ZeLFaDore** [TechFortress/GriefPrevention#833]
Quick question does griefprevention support dynmap like to tell people that others has claimed this area like this shown on the pic and if yes how to connect them up 

Image : https://ibb.co/pJzKFbJ

**Comment by FrozenBeard** [comment]
https://www.spigotmc.org/resources/jdynmapgriefprevention.818/

https://dev.bukkit.org/projects/dynmap-griefprevention

**Comment by RoboMWM** [comment]
FrozenBeard has listed one of many addons that do this - I think even the dynmap dev himself has an addon for GP.

**Comment by Laukage** [comment]
Both of those addons are either outdated or creates enormous lag.
last update 2016, and 2015...

**Comment by FrozenBeard** [comment]
> 
> 
> Both of those addons are either outdated or creates enormous lag.
> last update 2016, and 2015...

Then update them.

**Comment by Laukage** [comment]
> > Both of those addons are either outdated or creates enormous lag.
> > last update 2016, and 2015...
> 
> Then update them.

If i knew how, don't you think i would have done it already?
